const PageTitles = {
    '/': 'Home Page Title',
    '/about-us': 'About Us - Your Website Title',
    '/contact-us': 'Contact Us - Your Website Title',
    '/services/website-development': 'Website Development - Your Website Title',
    '/services/graphics-ui-ux': 'Graphics, UI/UX Design - Your Website Title',
    '/services/mobile-app-development': 'Mobile App Development - Best Mobile App Development Company in USA - Omka Tech',
    '/services/growth-marketing': 'Growth Marketing - Your Website Title',
    '/services/enterprise-software-solution': 'Enterprise Software Solutions - Your Website Title',
    '/services/e-commerce-web-apps': 'E-commerce Web Apps - Your Website Title',
    '/services/ready-made-solution': 'Ready-Made Solutions - Your Website Title',
    '/services/cms-design-development': 'CMS Design and Development - Your Website Title',
    '/privacy-policy': 'Privacy Policy - Your Website Title',
    '/term-condition': 'Terms and Conditions - Your Website Title',
    '/hire-resources': 'Hire Resources - Your Website Title',
    '/slider': 'Slider - Your Website Title',
    '/process': 'Process - Your Website Title',
    '/modal': 'Modal - Your Website Title',
    '/testimonial': 'Testimonials - Your Website Title',
    '/test': 'Test - Your Website Title',
    '/card': 'Course Card - Your Website Title',
    '/testi': 'Testimonials - Your Website Title',
    '/homeform': 'Home Form - Your Website Title',
    '/footer': 'Footer - Your Website Title',
    '/contactForm': 'Contact Form - Your Website Title',
    '/icon': 'Get in Touch - Your Website Title',
    '/emailForm': 'Email Form - Your Website Title',
    '/cardB': 'Card B - Your Website Title',
    '/blog': 'Blog - Your Website Title',
    '/blog/the-importance-of-digital-transformation-in-modern-business': 'The Importance of Digital Transformation in Modern Business - Your Website Title',
    '/blog/the-Pros-and-Cons-of-outsourcing-IT-services-for-your-business': 'The Pros and Cons of Outsourcing IT Services for Your Business - Your Website Title',
    '/blog/how-your-new-website-design-will-help-your-business-grow': 'How Your New Website Design Will Help Your Business Grow - Your Website Title',
    '/blog/how-ecommerce-website-development-is-necessary-for-a-business-to-succeed': 'How Ecommerce Website Development is Necessary for a Business to Succeed - Your Website Title',
    '/blog/top-reasons-why-strategies-fail': 'Top Reasons Why Strategies Fail - Your Website Title',
    '/blog/the-art-of-branding:-understanding-the-7-types-of-Logos': 'The Art of Branding: Understanding the 7 Types of Logos - Your Website Title',
    '/tools': 'Tools - Your Website Title',
    '/headBlog': 'Head Blog - Your Website Title',
    '/careers': 'Careers - Your Website Title',
    '/thankyou': 'Thank You - Your Website Title',
    '/HeadNav': 'Head Nav - Your Website Title',
    '/Youtube': 'YouTube - Your Website Title',
    '/Cards': 'Cards - Your Website Title',
    '/Connect': 'Connect - Your Website Title',
    '/Marquee': 'Marquee - Your Website Title',
    '/Main': 'Main - Your Website Title',
    '/CaseOne': 'Case One - Your Website Title',
  };
  
  export default PageTitles;
  